### ISSUE TITLE
Nicer Customer Frontend and Workflow

### ISSUE THREAD

**Issue by domwoe** [akscanb/smrtprpty#5]
1. Start screen with service explanation and price to rent the display + Button to create or restore wallet. This will open a modal showing the seed or give the possibility to enter the seed/password
2. See if Display is currently rented and for how long
3. See price and possibility to enter amount
4. Enter content to be shown and timer till authorization expires

**Comment by domwoe** [comment]
Base design could be something like this https://html5up.net/identity
or Google Material Design Cards

**Comment by akscanb** [comment]
Done!
